import Head from "next/head";
import React from "react";
import Link from "next/link";

function Header() {
  return (
    <>
      <Head>
        <title>Multi Language</title>
        <meta name="description" content="Generated by Dhaval Mak" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div class="header">
        <h1>Multi Language</h1>
      </div> */}
      <div class="topnav">
        <a>Multi Language</a>
        <Link href="/plugin">
          <a style={{ float: "right" }}>i18n trans. NPM ML</a>
        </Link>
        <Link href="/">
          <a style={{ float: "right" }}>Custom ML </a>
        </Link>
      </div>
    </>
  );
}

export default Header;
